services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: piyush
      POSTGRES_PASSWORD: piyush
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
     - proj1-basicflaskdockerpratice_postgres-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - proj1-basicflaskdockerpratice_postgres-network

volumes:
  postgres_data:

networks:
  proj1-basicflaskdockerpratice_postgres-network: